var cardName = {
    0: {name: 'attack',
        address:'images/Cards/AttackCard.jpg',
        effect: '',
        storedCard: ''},
    1: {name: 'shield',
        address:'images/Cards/ShieldCard.jpg' ,
        effect: '',
        storedCard: ''},
    2: {name: 'heal',
        address:'images/Cards/HealCard.jpg' ,
        effect: '',
        storedCard: ''},
    3: {name: 'bahamut',
        address:'images/Cards/BahamutCard.jpg' ,
        effect: '',
        storedCard: ''},
    4: {name: 'doubleStrike',
        address: 'images/Cards/DoubleStrikeCard.jpg',
        effect: '',
        storedCard: ''},
    5: {name: 'tripleStrike',
        address: 'images/Cards/TripleStrikeCard.jpg',
        effect: '',
        storedCard: ''},
    6: {name: 'terra2',
        address: 'images/Cards/AttackCard.jpg',
        effect: '',
        storedCard: ''},
    7: {name: 'ramuth',
        address: 'images/Cards/AttackCard.jpg',
        effect: '',
        storedCard: ''},
    8: {name: 'odin',
        address: 'images/Cards/AttackCard.jpg',
        effect: '',
        storedCard: ''},
};